[2022-05-01 17:29:21,517] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-01T17:19:15.565556+00:00 [queued]>
[2022-05-01 17:29:21,527] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-01T17:19:15.565556+00:00 [queued]>
[2022-05-01 17:29:21,528] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-01 17:29:21,530] {taskinstance.py:1250} INFO - Starting attempt 6 of 6
[2022-05-01 17:29:21,531] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-01 17:29:21,545] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_podsight_data> on 2022-05-01 17:19:15.565556+00:00
[2022-05-01 17:29:21,552] {standard_task_runner.py:52} INFO - Started process 699 to run task
[2022-05-01 17:29:21,555] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'podsight_ETL', 'extract_podsight_data', 'manual__2022-05-01T17:19:15.565556+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/podsight_ETL.py', '--cfg-path', '/tmp/tmp90ypzfi_', '--error-file', '/tmp/tmpc0licqq4']
[2022-05-01 17:29:21,556] {standard_task_runner.py:80} INFO - Job 44: Subtask extract_podsight_data
[2022-05-01 17:29:21,619] {logging_mixin.py:109} INFO - Running <TaskInstance: podsight_ETL.extract_podsight_data manual__2022-05-01T17:19:15.565556+00:00 [running]> on host ba3d3fc460bf
[2022-05-01 17:29:21,684] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=hamza.ahmed@liquidagency.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=podsight_ETL
AIRFLOW_CTX_TASK_ID=extract_podsight_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-01T17:19:15.565556+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-01T17:19:15.565556+00:00
[2022-05-01 17:29:21,687] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-01 17:29:21,688] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 "/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/podsight_API_JumpCloud.py"']
[2022-05-01 17:29:21,703] {subprocess.py:85} INFO - Output:
[2022-05-01 17:29:21,834] {subprocess.py:89} INFO - python3: can't open file '/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/podsight_API_JumpCloud.py': [Errno 2] No such file or directory
[2022-05-01 17:29:21,838] {subprocess.py:93} INFO - Command exited with return code 2
[2022-05-01 17:29:21,854] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-05-01 17:29:21,860] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=podsight_ETL, task_id=extract_podsight_data, execution_date=20220501T171915, start_date=20220501T172921, end_date=20220501T172921
[2022-05-01 17:29:21,880] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:108: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-05-01 17:29:21,883] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-05-01 17:29:21,884] {email.py:214} INFO - Email alerting: attempt 1
[2022-05-01 17:29:21,894] {configuration.py:381} WARNING - section/key [smtp/smtp_user] not found in config
[2022-05-01 17:29:21,895] {email.py:214} INFO - Email alerting: attempt 1
[2022-05-01 17:29:21,897] {taskinstance.py:1825} ERROR - Failed to send email to: ['hamza.ahmed@liquidagency.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1340, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1477, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1538, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2159, in email_alert
    send_email(self.task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 69, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 108, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 216, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 250, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1823, in handle_failure
    self.email_alert(error)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2161, in email_alert
    send_email(self.task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 69, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 108, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 216, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 250, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-05-01 17:29:21,918] {standard_task_runner.py:98} ERROR - Failed to execute job 44 for task extract_podsight_data (Bash command failed. The command returned a non-zero exit code 2.; 699)
[2022-05-01 17:29:21,931] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-01 17:29:21,973] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
