[2022-05-02 21:27:58,305] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_script.extract_data scheduled__2022-04-24T00:00:00+00:00 [queued]>
[2022-05-02 21:27:58,334] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_script.extract_data scheduled__2022-04-24T00:00:00+00:00 [queued]>
[2022-05-02 21:27:58,336] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 21:27:58,339] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-02 21:27:58,341] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 21:27:58,361] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_data> on 2022-04-24 00:00:00+00:00
[2022-05-02 21:27:58,378] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2022-05-02 21:27:58,389] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_script', 'extract_data', 'scheduled__2022-04-24T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/ETL_script.py', '--cfg-path', '/tmp/tmpar56nrld', '--error-file', '/tmp/tmp0yjbyzls']
[2022-05-02 21:27:58,390] {standard_task_runner.py:80} INFO - Job 135: Subtask extract_data
[2022-05-02 21:27:58,463] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL_script.extract_data scheduled__2022-04-24T00:00:00+00:00 [running]> on host 4c9d01f48299
[2022-05-02 21:27:58,526] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_script
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2022-04-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-24T00:00:00+00:00
[2022-05-02 21:27:58,528] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-02 21:27:58,529] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/API_extract.py']
[2022-05-02 21:27:58,542] {subprocess.py:85} INFO - Output:
[2022-05-02 21:27:58,544] {subprocess.py:89} INFO - bash: /Users/hamza.ahmed/Coding: No such file or directory
[2022-05-02 21:27:58,545] {subprocess.py:93} INFO - Command exited with return code 127
[2022-05-02 21:27:58,563] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-05-02 21:27:58,570] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_script, task_id=extract_data, execution_date=20220424T000000, start_date=20220502T212758, end_date=20220502T212758
[2022-05-02 21:27:58,594] {standard_task_runner.py:98} ERROR - Failed to execute job 135 for task extract_data (Bash command failed. The command returned a non-zero exit code 127.; 149)
[2022-05-02 21:27:58,639] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-02 21:27:58,720] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
