[2022-05-02 21:27:58,302] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_script.extract_data manual__2022-05-02T21:27:56.923195+00:00 [queued]>
[2022-05-02 21:27:58,337] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: ETL_script.extract_data manual__2022-05-02T21:27:56.923195+00:00 [queued]>
[2022-05-02 21:27:58,339] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 21:27:58,341] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-02 21:27:58,342] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 21:27:58,360] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): extract_data> on 2022-05-02 21:27:56.923195+00:00
[2022-05-02 21:27:58,366] {standard_task_runner.py:52} INFO - Started process 148 to run task
[2022-05-02 21:27:58,378] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_script', 'extract_data', 'manual__2022-05-02T21:27:56.923195+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/ETL_script.py', '--cfg-path', '/tmp/tmpeaprux6w', '--error-file', '/tmp/tmp1hhf5ge7']
[2022-05-02 21:27:58,380] {standard_task_runner.py:80} INFO - Job 134: Subtask extract_data
[2022-05-02 21:27:58,451] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL_script.extract_data manual__2022-05-02T21:27:56.923195+00:00 [running]> on host 4c9d01f48299
[2022-05-02 21:27:58,508] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_script
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-02T21:27:56.923195+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-02T21:27:56.923195+00:00
[2022-05-02 21:27:58,513] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-02 21:27:58,515] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/hamza.ahmed/Coding Projects/Python_Apps/Docker_Applications/Airflow_Docker_Apps/Python_Scripts/API_extract.py']
[2022-05-02 21:27:58,534] {subprocess.py:85} INFO - Output:
[2022-05-02 21:27:58,536] {subprocess.py:89} INFO - bash: /Users/hamza.ahmed/Coding: No such file or directory
[2022-05-02 21:27:58,538] {subprocess.py:93} INFO - Command exited with return code 127
[2022-05-02 21:27:58,555] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-05-02 21:27:58,566] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_script, task_id=extract_data, execution_date=20220502T212756, start_date=20220502T212758, end_date=20220502T212758
[2022-05-02 21:27:58,583] {standard_task_runner.py:98} ERROR - Failed to execute job 134 for task extract_data (Bash command failed. The command returned a non-zero exit code 127.; 148)
[2022-05-02 21:27:58,629] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-02 21:27:58,724] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
